package com.novastera.llamacpprn;

import androidx.annotation.Nullable;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.bridge.WritableMap;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;

/**
 * Abstract base class that would normally be generated by the React Native codegen.
 * This is the spec class for the Turbo Module.
 */
public abstract class NativeLlamaCppRnSpec extends ReactContextBaseJavaModule implements TurboModule {
    public NativeLlamaCppRnSpec(ReactApplicationContext reactContext) {
        super(reactContext);
    }

    /**
     * Initialize a Llama context with the given model parameters
     */
    public abstract void initLlama(ReadableMap params, Promise promise);

    /**
     * Load model info without creating a full context
     */
    public abstract void loadLlamaModelInfo(String modelPath, Promise promise);

    /**
     * Convert JSON schema to GBNF grammar
     */
    public abstract void jsonSchemaToGbnf(ReadableMap schema, Promise promise);
} 